import VariableProximity from './components/VariableProximity';import{usePortfolioMotion}from'./hooks/usePortfolioMotion';import{useState}from'react';import worksData from'./works.json';
type Work={id:string;category:string;series:string;title:string;src:string;type:'image'|'video';poster:string|null};
const works=worksData as Work[];const filters=[['全部','全部'],['个人 IP','个人 IP'],['东方视觉','东方视觉探索'],['叙事','叙事'],['动态','动态'],['其他','其他']];
function Logo(){return <a className="logo" href="#top">闲人<small>XIANREN</small></a>}
export default function App(){usePortfolioMotion();const grayHero=new URLSearchParams(window.location.search).get('hero')==='gray';const[filter,setFilter]=useState('全部'),[open,setOpen]=useState<Work|null>(null);const shown=filter==='全部'?works:works.filter(w=>w.category===filter);const groups=Object.entries(shown.reduce<Record<string,Work[]>>((a,w)=>{(a[w.series]??=[]).push(w);return a},{}));return <main><div className="opening" aria-hidden="true"><i className="openingPanel openingPanel--top"/><i className="openingPanel openingPanel--bottom"/><b className="openingMark">XIANREN</b></div>
<section className={`hero${grayHero?' heroGray':''}`} id="top">{!grayHero&&<><video className="heroVideo" src="/portfolio-v5/hero-background-57ccad42a61c.mp4" poster="/portfolio-v5/hero-cover-4115e7a81e36.webp" autoPlay muted loop playsInline/><div className="heroShade"/></>}<header className="frame"><Logo/><nav><a href="#works">作品</a><a href="#about">关于</a><a href="#thinking">想法</a><a href="#contact">联系</a></nav></header><div className="heroTitle frame"><h1><VariableProximity label={"和 AI 一起，\n边想边做。"} radius={240}/></h1><p>我是闲人，一个普通的 AI 交流者。<br/>这里记录对话、练习、实验，以及逐渐形成的作品。</p></div><div className="heroBottom frame"><span>THINK / PRACTICE / LEARN / MAKE</span><a href="#works">向下浏览 ↓</a></div></section>
<section className="about frame" id="about"><div className="sectionWord" aria-hidden="true">ABOUT</div><span>01 / ABOUT</span><h2><VariableProximity label={"一个正在与 AI\n交流、学习和创作\n的普通人。"} radius={210}/></h2><div className="aboutText"><p>我对图像、设计和新工具保持好奇。通过不断与 AI 交流，我学习如何提出问题、描述感受，也尝试把脑海中模糊的想法变成可以看见的东西。</p><p>我曾以为，“闲”会自然带来灵感。后来发现，好的作品来自持续思考、反复练习、主动学习和真正去做。</p></div></section>
<section className="works" id="works"><div className="sectionWord" aria-hidden="true">WORKS</div><div className="worksHead frame"><span>02 / WORKS</span><h2><VariableProximity label="作品档案" radius={190}/> <small>{String(shown.length).padStart(2,'0')}</small></h2><div className="filters">{filters.map(f=><button className={filter===f[1]?'active':''} onClick={()=>setFilter(f[1])} key={f[1]}>{f[0]}</button>)}</div></div><div className="seriesList">{groups.map(([series,items],gi)=><section className="seriesBlock" key={series}><div className="seriesIntro frame"><span>{String(gi+1).padStart(2,'0')} / SERIES</span><h3><VariableProximity label={series} radius={190}/></h3><p>{items[0].category}<br/>{String(items.length).padStart(2,'0')} WORKS</p></div><div className="gallery">{items.map(w=><button className="work" onClick={()=>setOpen(w)} key={w.id}>{w.type==='video'?<video poster={w.poster||undefined} preload="none" muted playsInline/>:<img src={w.src} alt={w.title} loading="lazy" decoding="async"/>}<span className="overlay"><b>{w.series}</b><small>{w.category} / {w.type==='video'?'VIDEO':'IMAGE'}</small><i>{w.type==='video'?'PLAY':'VIEW'} · {w.id}</i></span>{w.type==='video'&&<span className="play">▶</span>}</button>)}</div></section>)}</div></section>
<section className="thinking frame" id="thinking"><div className="sectionWord" aria-hidden="true">THINK</div><span>03 / STATEMENT</span><h2><VariableProximity label={"不等灵感，\n在交流与练习中\n让作品发生。"} radius={230}/></h2><div className="steps"><p><b>01</b>思考 THINK</p><p><b>02</b>交流 TALK</p><p><b>03</b>练习 PRACTICE</p><p><b>04</b>行动 MAKE</p></div></section>
<section className="contact" id="contact"><div className="sectionWord" aria-hidden="true">CONTACT</div><div className="frame"><span>04 / CONTACT</span><p>如果你也在尝试用 AI 理解、表达或创造一些东西，<br/>欢迎从一次简单的交流开始。</p><h2><VariableProximity label={"要不要一起，\n边想边做？"} radius={230}/></h2><a className="mail" href="mailto:hello@xianren.studio">hello@xianren.studio ↗</a><footer><Logo/><span>© 2026 XIANREN</span><span>一个人与 AI 的创作档案</span><a href="#top">TOP ↑</a></footer></div></section>
{open&&<div className="lightbox" onClick={()=>setOpen(null)} role="dialog" aria-modal="true"><button aria-label="关闭">关闭 ×</button><div className="lightboxMedia" onClick={e=>e.stopPropagation()}>{open.type==='video'?<video src={open.src} poster={open.poster||undefined} controls autoPlay playsInline/>:<img src={open.src} alt={open.title}/>}<p>{open.series}<small>{open.category} / {open.title}</small></p></div></div>}</main>}